# Alura Challenge Data Science - Semana 1

## Primeiros passos em Data Science - limpeza dos dados trazidos de uma API

#### Dicionário de dados

* `customerID`: número de identificação único de cada cliente
* `Churn`: se o cliente deixou ou não a empresa 
* `gender`: gênero (masculino e feminino) 
* `SeniorCitizen`: informação sobre um cliente ter ou não idade igual ou maior que 65 anos 
* `Partner`:  se o cliente possui ou não um parceiro ou parceira
* `Dependents`: se o cliente possui ou não dependentes
* `tenure`:  meses de contrato do cliente
* `PhoneService`: assinatura de serviço telefônico 
* `MultipleLines`: assisnatura de mais de uma linha de telefone 
* `InternetService`: assinatura de um provedor internet 
* `OnlineSecurity`: assinatura adicional de segurança online 
* `OnlineBackup`: assinatura adicional de backup online 
* `DeviceProtection`: assinatura adicional de proteção no dispositivo 
* `TechSupport`: assinatura adicional de suporte técnico, menos tempo de espera
* `StreamingTV`: assinatura de TV a cabo 
* `StreamingMovies`: assinatura de streaming de filmes 
* `Contract`: tipo de contrato
* `PaperlessBilling`: se o cliente prefere receber online a fatura
* `PaymentMethod`: forma de pagamento
* `Charges.Monthly`: total de todos os serviços do cliente por mês
* `Charges.Total`: total gasto pelo cliente

In [1]:
#Importando Bibliotecas

import pandas as pd
import numpy as np

In [2]:
#Configurações de exibição

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", None)

In [3]:
# Importando os dados

data = pd.read_json(
    path_or_buf = 'dataset/Telco-Customer-Churn.json',
    orient='columns')
data.head(10)

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Partner': 'Yes', 'Dependents': 'Yes', 'tenure': 9}","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': 'No', 'OnlineBackup': 'Yes', 'DeviceProtection': 'No', 'TechSupport': 'Yes', 'StreamingTV': 'Yes', 'StreamingMovies': 'No'}","{'Contract': 'One year', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Mailed check', 'Charges': {'Monthly': 65.6, 'Total': '593.3'}}"
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partner': 'No', 'Dependents': 'No', 'tenure': 9}","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': 'No', 'OnlineBackup': 'No', 'DeviceProtection': 'No', 'TechSupport': 'No', 'StreamingTV': 'No', 'StreamingMovies': 'Yes'}","{'Contract': 'Month-to-month', 'PaperlessBilling': 'No', 'PaymentMethod': 'Mailed check', 'Charges': {'Monthly': 59.9, 'Total': '542.4'}}"
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partner': 'No', 'Dependents': 'No', 'tenure': 4}","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecurity': 'No', 'OnlineBackup': 'No', 'DeviceProtection': 'Yes', 'TechSupport': 'No', 'StreamingTV': 'No', 'StreamingMovies': 'No'}","{'Contract': 'Month-to-month', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Electronic check', 'Charges': {'Monthly': 73.9, 'Total': '280.85'}}"
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partner': 'Yes', 'Dependents': 'No', 'tenure': 13}","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecurity': 'No', 'OnlineBackup': 'Yes', 'DeviceProtection': 'Yes', 'TechSupport': 'No', 'StreamingTV': 'Yes', 'StreamingMovies': 'Yes'}","{'Contract': 'Month-to-month', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Electronic check', 'Charges': {'Monthly': 98.0, 'Total': '1237.85'}}"
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Partner': 'Yes', 'Dependents': 'No', 'tenure': 3}","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecurity': 'No', 'OnlineBackup': 'No', 'DeviceProtection': 'No', 'TechSupport': 'Yes', 'StreamingTV': 'Yes', 'StreamingMovies': 'No'}","{'Contract': 'Month-to-month', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Mailed check', 'Charges': {'Monthly': 83.9, 'Total': '267.4'}}"
5,0013-MHZWF,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Partner': 'No', 'Dependents': 'Yes', 'tenure': 9}","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': 'No', 'OnlineBackup': 'No', 'DeviceProtection': 'No', 'TechSupport': 'Yes', 'StreamingTV': 'Yes', 'StreamingMovies': 'Yes'}","{'Contract': 'Month-to-month', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Credit card (automatic)', 'Charges': {'Monthly': 69.4, 'Total': '571.45'}}"
6,0013-SMEOE,No,"{'gender': 'Female', 'SeniorCitizen': 1, 'Partner': 'Yes', 'Dependents': 'No', 'tenure': 71}","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecurity': 'Yes', 'OnlineBackup': 'Yes', 'DeviceProtection': 'Yes', 'TechSupport': 'Yes', 'StreamingTV': 'Yes', 'StreamingMovies': 'Yes'}","{'Contract': 'Two year', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Bank transfer (automatic)', 'Charges': {'Monthly': 109.7, 'Total': '7904.25'}}"
7,0014-BMAQU,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partner': 'Yes', 'Dependents': 'No', 'tenure': 63}","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecurity': 'Yes', 'OnlineBackup': 'No', 'DeviceProtection': 'No', 'TechSupport': 'Yes', 'StreamingTV': 'No', 'StreamingMovies': 'No'}","{'Contract': 'Two year', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Credit card (automatic)', 'Charges': {'Monthly': 84.65, 'Total': '5377.8'}}"
8,0015-UOCOJ,No,"{'gender': 'Female', 'SeniorCitizen': 1, 'Partner': 'No', 'Dependents': 'No', 'tenure': 7}","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': 'Yes', 'OnlineBackup': 'No', 'DeviceProtection': 'No', 'TechSupport': 'No', 'StreamingTV': 'No', 'StreamingMovies': 'No'}","{'Contract': 'Month-to-month', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Electronic check', 'Charges': {'Monthly': 48.2, 'Total': '340.35'}}"
9,0016-QLJIS,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Partner': 'Yes', 'Dependents': 'Yes', 'tenure': 65}","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': 'Yes', 'OnlineBackup': 'Yes', 'DeviceProtection': 'Yes', 'TechSupport': 'Yes', 'StreamingTV': 'Yes', 'StreamingMovies': 'Yes'}","{'Contract': 'Two year', 'PaperlessBilling': 'Yes', 'PaymentMethod': 'Mailed check', 'Charges': {'Monthly': 90.45, 'Total': '5957.9'}}"

Extração de dados das colunas:

In [4]:
# Normalize customer

data_customer = pd.json_normalize(data=data.customer)
data_customer.head(10)

   gender  SeniorCitizen Partner Dependents  tenure
0  Female              0     Yes        Yes       9
1    Male              0      No         No       9
2    Male              0      No         No       4
3    Male              1     Yes         No      13
4  Female              1     Yes         No       3
5  Female              0      No        Yes       9
6  Female              1     Yes         No      71
7    Male              0     Yes         No      63
8  Female              1      No         No       7
9  Female              0     Yes        Yes      65

In [5]:
# Normalize phone

data_phone = pd.json_normalize(data=data.phone)
data_phone.head(10)

  PhoneService MultipleLines
0          Yes            No
1          Yes           Yes
2          Yes            No
3          Yes            No
4          Yes            No
5          Yes            No
6          Yes            No
7          Yes           Yes
8          Yes            No
9          Yes           Yes

In [6]:
# Normalize internet

data_internet = pd.json_normalize(data=data.internet)
data_internet.head(10)

,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,DSL,No,Yes,No,Yes,Yes,No
1,DSL,No,No,No,No,No,Yes
2,Fiber optic,No,No,Yes,No,No,No
3,Fiber optic,No,Yes,Yes,No,Yes,Yes
4,Fiber optic,No,No,No,Yes,Yes,No
5,DSL,No,No,No,Yes,Yes,Yes
6,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes
7,Fiber optic,Yes,No,No,Yes,No,No
8,DSL,Yes,No,No,No,No,No
9,DSL,Yes,Yes,Yes,Yes,Yes,Yes

In [7]:
# Normalize account

data_account = pd.json_normalize(data=data.account)
data_account.head(10)

,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,One year,Yes,Mailed check,65.60,593.3
1,Month-to-month,No,Mailed check,59.90,542.4
2,Month-to-month,Yes,Electronic check,73.90,280.85
3,Month-to-month,Yes,Electronic check,98.00,1237.85
4,Month-to-month,Yes,Mailed check,83.90,267.4
5,Month-to-month,Yes,Credit card (automatic),69.40,571.45
6,Two year,Yes,Bank transfer (automatic),109.70,7904.25
7,Two year,Yes,Credit card (automatic),84.65,5377.8
8,Month-to-month,Yes,Electronic check,48.20,340.35
9,Two year,Yes,Mailed check,90.45,5957.9

In [8]:
# Concatenado Dataframe principal com os normalizados

data_final = pd.concat([data, data_customer], axis='columns')
data_final = pd.concat([data_final, data_phone], axis='columns')
data_final = pd.concat([data_final, data_internet], axis='columns')
data_final = pd.concat([data_final, data_account], axis='columns')

# Removendo as colunas que não serão utilizadas

data_final.drop(columns='customer', inplace=True)
data_final.drop(columns='phone', inplace=True)
data_final.drop(columns='internet', inplace=True)
data_final.drop(columns='account', inplace=True)

data_final.head(5)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

Tratamento de dados

In [9]:
# Tradução do dataset

data_final.columns = ['ClienteId', 'ClienteCancelado', 'Gênero', 'Idoso', 'Parceiro', 'Dependentes', 'TempoContrato', 'ServiçoTelefone', 'MultiplasLinhas',
                      'ServiçoInternet', 'SegurançaOnline', 'BackupOnline', 'ProteçãoDispositivo', 'SuporteTecnico', 'StreamingTV', 'StreamingFilmes',
                      'Contrato', 'FaturaSemPapel', 'FormaPagamento', 'CobrançaMensal', 'CobrançaTotal']

In [10]:
# Verificando a existencia de dados nulos no Dataframe

data_final.isnull().sum()

ClienteId              0
ClienteCancelado       0
Gênero                 0
Idoso                  0
Parceiro               0
Dependentes            0
TempoContrato          0
ServiçoTelefone        0
MultiplasLinhas        0
ServiçoInternet        0
SegurançaOnline        0
BackupOnline           0
ProteçãoDispositivo    0
SuporteTecnico         0
StreamingTV            0
StreamingFilmes        0
Contrato               0
FaturaSemPapel         0
FormaPagamento         0
CobrançaMensal         0
CobrançaTotal          0
dtype: int64

Verificar dados faltantes

In [11]:
data_final.ClienteId.value_counts()

0002-ORFBO    1
6614-VBEGU    1
6637-KYRCV    1
6635-MYYYZ    1
6635-CPNUN    1
             ..
3374-TTZTK    1
3374-PZLXD    1
3374-LXDEV    1
3373-YZZYM    1
9995-HOTOH    1
Name: ClienteId, Length: 7267, dtype: int64

In [12]:
data_final.ClienteCancelado.value_counts()

# 224 valores vazios

No     5174
Yes    1869
        224
Name: ClienteCancelado, dtype: int64

In [13]:
data_final.Gênero.value_counts()

Male      3675
Female    3592
Name: Gênero, dtype: int64

In [14]:
data_final.Idoso.value_counts()

0    6085
1    1182
Name: Idoso, dtype: int64

In [15]:
data_final.Parceiro.value_counts()

No     3749
Yes    3518
Name: Parceiro, dtype: int64

In [16]:
data_final.Dependentes.value_counts()

No     5086
Yes    2181
Name: Dependentes, dtype: int64

In [17]:
data_final.TempoContrato.value_counts()
# 11 não completaram 1 mes de contrato

1     634
72    369
2     246
3     207
4     185
     ...
38     60
39     59
44     54
36     50
0      11
Name: TempoContrato, Length: 73, dtype: int64

In [18]:
data_final.ServiçoTelefone.value_counts()

Yes    6560
No      707
Name: ServiçoTelefone, dtype: int64

In [19]:
data_final.MultiplasLinhas.value_counts()

No                  3495
Yes                 3065
No phone service     707
Name: MultiplasLinhas, dtype: int64

In [20]:
data_final.ServiçoInternet.value_counts()

Fiber optic    3198
DSL            2488
No             1581
Name: ServiçoInternet, dtype: int64

In [21]:
data_final.SegurançaOnline.value_counts()

No                     3608
Yes                    2078
No internet service    1581
Name: SegurançaOnline, dtype: int64

In [22]:
data_final.BackupOnline.value_counts()

No                     3182
Yes                    2504
No internet service    1581
Name: BackupOnline, dtype: int64

In [23]:
data_final.ProteçãoDispositivo.value_counts()

No                     3195
Yes                    2491
No internet service    1581
Name: ProteçãoDispositivo, dtype: int64

In [24]:
data_final.SuporteTecnico.value_counts()

No                     3582
Yes                    2104
No internet service    1581
Name: SuporteTecnico, dtype: int64

In [25]:
data_final.StreamingTV.value_counts()

No                     2896
Yes                    2790
No internet service    1581
Name: StreamingTV, dtype: int64

In [26]:
data_final.StreamingFilmes.value_counts()

No                     2870
Yes                    2816
No internet service    1581
Name: StreamingFilmes, dtype: int64

In [27]:
data_final.Contrato.value_counts()

Month-to-month    4005
Two year          1743
One year          1519
Name: Contrato, dtype: int64

In [28]:
data_final.FaturaSemPapel.value_counts()

Yes    4311
No     2956
Name: FaturaSemPapel, dtype: int64

In [29]:
data_final.FormaPagamento.value_counts()

Electronic check             2445
Mailed check                 1665
Bank transfer (automatic)    1589
Credit card (automatic)      1568
Name: FormaPagamento, dtype: int64

In [30]:
data_final.CobrançaMensal.value_counts()

20.05     65
19.85     46
19.90     46
19.70     45
19.55     45
          ..
23.45      1
116.55     1
106.85     1
68.55      1
67.85      1
Name: CobrançaMensal, Length: 1585, dtype: int64

In [31]:
data_final.CobrançaTotal.value_counts().sort_index()

# 11 valores que estão como 'vazios', pode estar relacionado com os clientes que tem menos de 1 mes de contrato

          11
100.2      1
100.25     1
100.35     1
100.4      1
          ..
997.75     1
998.1      1
999.45     2
999.8      1
999.9      1
Name: CobrançaTotal, Length: 6531, dtype: int64

In [32]:
data_final.query("CobrançaTotal == ' '")

,ClienteId,ClienteCancelado,Gênero,Idoso,Parceiro,Dependentes,TempoContrato,ServiçoTelefone,MultiplasLinhas,ServiçoInternet,SegurançaOnline,BackupOnline,ProteçãoDispositivo,SuporteTecnico,StreamingTV,StreamingFilmes,Contrato,FaturaSemPapel,FormaPagamento,CobrançaMensal,CobrançaTotal
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

In [33]:
data_final.query("TempoContrato == 0")

,ClienteId,ClienteCancelado,Gênero,Idoso,Parceiro,Dependentes,TempoContrato,ServiçoTelefone,MultiplasLinhas,ServiçoInternet,SegurançaOnline,BackupOnline,ProteçãoDispositivo,SuporteTecnico,StreamingTV,StreamingFilmes,Contrato,FaturaSemPapel,FormaPagamento,CobrançaMensal,CobrançaTotal
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

In [34]:
# Podemos corrigir os valores vazios da coluna 'CobrançaTotal' por 0

data_final.CobrançaTotal = data_final.CobrançaTotal.replace(' ', '0')

In [58]:
# Após algumas sugestões, percebi que o ideal seria manter a coluna 'CobrançaTotal' com valores iguais a coluna 'CobrançaMensal'
# nos casos que clientes não completaram 1 mes de contrato

cobrancaTotal = lambda data: data['CobrançaMensal'] if data['CobrançaTotal'] == 0 else data['CobrançaTotal']
data_final.CobrançaTotal = data_final.apply(cobrancaTotal, axis = 1)

In [59]:
# Conferencia da substituição de valores

data_final.query("TempoContrato == 0")

,ClienteId,ClienteCancelado,Gênero,Idoso,Parceiro,Dependentes,TempoContrato,ServiçoTelefone,MultiplasLinhas,ServiçoInternet,SegurançaOnline,BackupOnline,ProteçãoDispositivo,SuporteTecnico,StreamingTV,StreamingFilmes,Contrato,FaturaSemPapel,FormaPagamento,ContasDiarias,CobrançaMensal,CobrançaTotal
975,1371-DWPAZ,No,Female,No,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),1.87,56.05,56.05
1775,2520-SGTTA,No,Female,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0.67,20.00,20.00
1955,2775-SEFEE,No,Male,No,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),2.06,61.90,61.90
2075,2923-ARZLG,No,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,0.66,19.70,19.70
2232,3115-CZMZD,No,Male,No,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0.68,20.25,20.25
2308,3213-VVOLG,No,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0.85,25.35,25.35
2930,4075-WKNIU,No,Female,No,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,2.44,73.35,73.35
3134,4367-NUYAO,No,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0.86,25.75,25.75
3203,4472-LVYGI,No,Female,No,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),1.75,52.55,52.55
4169,5709-LVOEQ,No,Female,No,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,2.70,80.85,80.85
5599,7644-OMVMY,No,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0.66,19.85,19.85

In [56]:
# Tipo de Dados

data_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ClienteId            7043 non-null   object
 1   ClienteCancelado     7043 non-null   object
 2   Gênero               7043 non-null   object
 3   Idoso                7043 non-null   object
 4   Parceiro             7043 non-null   object
 5   Dependentes          7043 non-null   object
 6   TempoContrato        7043 non-null   int64
 7   ServiçoTelefone      7043 non-null   object
 8   MultiplasLinhas      7043 non-null   object
 9   ServiçoInternet      7043 non-null   object
 10  SegurançaOnline      7043 non-null   object
 11  BackupOnline         7043 non-null   object
 12  ProteçãoDispositivo  7043 non-null   object
 13  SuporteTecnico       7043 non-null   object
 14  StreamingTV          7043 non-null   object
 15  StreamingFilmes      7043 non-null   object
 16  Contrato             7043 non-null   object
 17  FaturaSemPapel       7043 non-null   object
 18  FormaPagamento       7043 non-null   object
 19  ContasDiarias        7043 non-null   float64
 20  CobrançaMensal       7043 non-null   float64
 21  CobrançaTotal        7043 non-null   float64
dtypes: float64(3), int64(1), object(18)
memory usage: 1.2+ MB

In [39]:
# A coluna 'CobrançaTotal' está como 'object' no tipo de dados, mas por se tratar de valores, a mesma será convertida em 'float'

data_final['CobrançaTotal'] = pd.to_numeric(data_final['CobrançaTotal'], errors='coerce')
data_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ClienteId            7267 non-null   object
 1   ClienteCancelado     7267 non-null   object
 2   Gênero               7267 non-null   object
 3   Idoso                7267 non-null   int64
 4   Parceiro             7267 non-null   object
 5   Dependentes          7267 non-null   object
 6   TempoContrato        7267 non-null   int64
 7   ServiçoTelefone      7267 non-null   object
 8   MultiplasLinhas      7267 non-null   object
 9   ServiçoInternet      7267 non-null   object
 10  SegurançaOnline      7267 non-null   object
 11  BackupOnline         7267 non-null   object
 12  ProteçãoDispositivo  7267 non-null   object
 13  SuporteTecnico       7267 non-null   object
 14  StreamingTV          7267 non-null   object
 15  StreamingFilmes      7267 non-null   object
 16  Contrato             7267 non-null   object
 17  FaturaSemPapel       7267 non-null   object
 18  FormaPagamento       7267 non-null   object
 19  CobrançaMensal       7267 non-null   float64
 20  CobrançaTotal        7267 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [40]:
# os valores vazios da coluna 'ClienteCancelado' não interessa, uma vez que queremos saber a taxa de cancelamento 

data_final = data_final.drop(data_final[data_final.ClienteCancelado == ''].index, axis=0) 
data_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ClienteId            7043 non-null   object
 1   ClienteCancelado     7043 non-null   object
 2   Gênero               7043 non-null   object
 3   Idoso                7043 non-null   int64
 4   Parceiro             7043 non-null   object
 5   Dependentes          7043 non-null   object
 6   TempoContrato        7043 non-null   int64
 7   ServiçoTelefone      7043 non-null   object
 8   MultiplasLinhas      7043 non-null   object
 9   ServiçoInternet      7043 non-null   object
 10  SegurançaOnline      7043 non-null   object
 11  BackupOnline         7043 non-null   object
 12  ProteçãoDispositivo  7043 non-null   object
 13  SuporteTecnico       7043 non-null   object
 14  StreamingTV          7043 non-null   object
 15  StreamingFilmes      7043 non-null   object
 16  Contrato             7043 non-null   object
 17  FaturaSemPapel       7043 non-null   object
 18  FormaPagamento       7043 non-null   object
 19  CobrançaMensal       7043 non-null   float64
 20  CobrançaTotal        7043 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [41]:
# A notação Boleana da da coluna 'Idoso' está em um padrão diferente das demais, logo foi feita a conversão desses valores

data_final.Idoso.value_counts()

0    5901
1    1142
Name: Idoso, dtype: int64

In [42]:
# Feita a alteração, onde o '0' foi substituido por 'No', e '1' por 'Yes'

for idoso in 'Idoso':
    data_final['Idoso'] = data_final['Idoso'].replace({0: "No", 1: "Yes"})

data_final.Idoso.head(10)

0     No
1     No
2     No
3    Yes
4    Yes
5     No
6    Yes
7     No
8    Yes
9     No
Name: Idoso, dtype: object

In [43]:
# Criando coluna Contas diárias
# Os gastos diários serão a divisão dos valores da coluna 'Cobrança_Mensal' divididos por 30 dias

data_final_contas_diarias = round(data_final['CobrançaMensal'] / 30, 2)

data_final.insert(loc = 19, column = 'ContasDiarias', value = data_final_contas_diarias) 

data_final.head(10)

,ClienteId,ClienteCancelado,Gênero,Idoso,Parceiro,Dependentes,TempoContrato,ServiçoTelefone,MultiplasLinhas,ServiçoInternet,SegurançaOnline,BackupOnline,ProteçãoDispositivo,SuporteTecnico,StreamingTV,StreamingFilmes,Contrato,FaturaSemPapel,FormaPagamento,ContasDiarias,CobrançaMensal,CobrançaTotal
0,0002-ORFBO,No,Female,No,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,2.19,65.60,593.30
1,0003-MKNFE,No,Male,No,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,2.00,59.90,542.40
2,0004-TLHLJ,Yes,Male,No,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,2.46,73.90,280.85
3,0011-IGKFF,Yes,Male,Yes,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,3.27,98.00,1237.85
4,0013-EXCHZ,Yes,Female,Yes,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,2.80,83.90,267.40
5,0013-MHZWF,No,Female,No,No,Yes,9,Yes,No,DSL,No,No,No,Yes,Yes,Yes,Month-to-month,Yes,Credit card (automatic),2.31,69.40,571.45
6,0013-SMEOE,No,Female,Yes,Yes,No,71,Yes,No,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),3.66,109.70,7904.25
7,0014-BMAQU,No,Male,No,Yes,No,63,Yes,Yes,Fiber optic,Yes,No,No,Yes,No,No,Two year,Yes,Credit card (automatic),2.82,84.65,5377.80
8,0015-UOCOJ,No,Female,Yes,No,No,7,Yes,No,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,1.61,48.20,340.35
9,0016-QLJIS,No,Female,No,Yes,Yes,65,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,3.02,90.45,5957.90

In [60]:
# Exportando os Dados para um arquivo .csv

data_final.to_csv(path_or_buf = 'dataset/Telco-Customer-Churn-Tratado.csv', index = False)